# Generated by Django 5.2.17 on 2026-10-04 04:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('offset', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(unique=True)),
                ('chat_id', models.BigIntegerField()),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=2000)),
                ('city', models.CharField(default='Алматы', max_length=80)),
                ('photo', models.FileField(blank=True, upload_to='jobs/')),
                ('photo_rights', models.BooleanField(default=False)),
                ('auto_publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('GENERATING', 'Подготовка'), ('DRAFT', 'Черновик'), ('QUEUED', 'В очереди'), ('CREATING', 'Создание контейнера'), ('WAITING', 'Обработка фотографии'), ('PUBLISHING', 'Публикация'), ('PUBLISHED', 'Опубликован'), ('DEMO', 'Тест завершён'), ('FAILED', 'Ошибка'), ('UNCERTAIN', 'Нужна сверка с Instagram'), ('CANCELLED', 'Отменён')], default='GENERATING', max_length=20)),
                ('caption', models.TextField(blank=True)),
                ('container_id', models.CharField(blank=True, max_length=100)),
                ('media_id', models.CharField(blank=True, max_length=100)),
                ('permalink', models.URLField(blank=True)),
                ('media_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='studio.job')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('INVITED', 'Приглашён'), ('CONSENT', 'Согласие на AI'), ('CHATTING', 'Диалог'), ('APPROVAL', 'Подтверждение отзыва'), ('PUBLIC', 'Разрешение публикации'), ('DONE', 'Готово'), ('STOPPED', 'Остановлен')], default='INVITED', max_length=20)),
                ('ai_consent', models.BooleanField(default=False)),
                ('public_consent', models.BooleanField(default=False)),
                ('history', models.JSONField(default=list)),
                ('answers', models.JSONField(default=list)),
                ('approved_text', models.TextField(blank=True)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='studio.job')),
            ],
        ),
    ]
