# Generated by Django 5.2.17 on 2026-10-04 04:50

import studio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_demo',
            field=models.BooleanField(default=studio.models.demo_default, editable=False),
        ),
    ]
